### ISSUE TITLE
Works in Chrome not in Firefox

### ISSUE THREAD

**Issue by GrumpyOldDM** [GrumpyOldDM/STA_DemoSheet#3]
The Settings button appears to only work in Chrome (tested this morning before moving to Roll20 - working on it now)

**Comment by RandallBurt** [comment]
Poop. Sorry about that. Let me k ow if i can help.

**Comment by GrumpyOldDM** [comment]
I found how to fix it, added a   -moz-appearance: none;  - sadly the toggle isn't working quite right on Firefox.

**Comment by GrumpyOldDM** [comment]
Ok I've updated the master with the css fixes for Firefox -  a few tweaks - nothing too major, but the sheet now looks the same across FireFox and Chrome. Bigger problem is the sheet change - the logic is very inconsisent - sometimes I've gotten it to work in Firefox othertimes it just won't change. Want to see if you can figure it out @RandallBurt?

**Comment by RandallBurt** [comment]
Yeah, ill check it out this evening after the day job.

**Comment by RandallBurt** [comment]
@GrumpyOldDM 
So I think I got the checkboxes sorted for the most part. Something small
is broken with my worker script that syncs the amount of stress/shields
with the checkboxes, but I should be able to sort that fairly quickly
tomorrow.

I also noticed that the lined textareas are displaying funny in Firefox and
did some research and its just how the control is built on that browser.
I've played around with some alternatives that should work in Chrome and
Firefox, but not happy with it just yet. Gonna log for the night and
hopefully finish this up tomorrow after work.

**Comment by RandallBurt** [comment]
Closed by #4. Should maybe raise a separate issue for the `textarea` issue?

**Comment by GrumpyOldDM** [comment]
I think this version looks great, works good on Chrome and Firefox - the textarea seems minor enough - I'll go ahead and close this one out and submit this version up to the roll20 repository, we can work on the textarea tweaks in a future version.
